# Generated by Django 5.0.7 on 2024-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('items', models.JSONField(blank=True, default=dict, null=True)),
                ('lat_long', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('full_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
